### ISSUE TITLE
Getting Started: Broken link to "Mylyn Quick Reference Guide"

### ISSUE THREAD

**Issue by Chealer** [eclipse-mylyn/mylyn-website#6]
[The _Get Started_ page](https://eclipse.dev/mylyn/start/) has a link to http://www.tasktop.com/mylyn/, labelled as Mylyn's "[Quick Reference Guide](http://www.tasktop.com/mylyn/)". While that link does yield a webpage, it says nothing about Mylyn.

The Wayback Machine shows that [at the end of 2008, the linked page used to](https://web.archive.org/web/20081211200327/http://www.tasktop.com/mylyn/) mention Mylyn, but it itself only **linked** to a _Mylyn Quick Reference Guide_, and it required registration.

**Comment by BeckerFrank** [comment]
All links to http://tasktop.com are no longer working as Tasktop is now part of https://www.planview.com and I cannot find the targets, some other are also no longer valid. So we end up with only two links and remove the rest
